What happens if you register a function with `atexit`, within a function invoked by a call to `exit`?
